"""omega briefing — Intelligence briefing generator: auto-compile markdown + HTML
daily intelligence brief from all recent omega reports for a target."""
from __future__ import annotations
import json, os, re, glob, datetime
from typing import Any
from rich.console import Console
from rich.panel import Panel
from rich import box

console = Console()

HTML_BRIEF = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Omega Intelligence Brief — {target}</title>
<style>
  :root {{ --bg:#0d0d0d; --surface:#141414; --border:#222; --accent:#ff2d78; --text:#e0e0e0; --dim:#555; --cyan:#00d4ff; --green:#39ff14; --yellow:#ffd700; --red:#ff4444; }}
  * {{ box-sizing:border-box; margin:0; padding:0; }}
  body {{ background:var(--bg); color:var(--text); font-family:'Segoe UI',system-ui,sans-serif; font-size:14px; max-width:960px; margin:0 auto; padding:24px; }}
  h1 {{ color:var(--accent); font-size:28px; letter-spacing:3px; margin-bottom:4px; }}
  h2 {{ color:var(--cyan); font-size:16px; text-transform:uppercase; letter-spacing:2px; margin:28px 0 12px; border-bottom:1px solid var(--border); padding-bottom:6px; }}
  h3 {{ color:var(--accent); font-size:13px; margin:16px 0 6px; }}
  .meta {{ color:var(--dim); font-size:12px; margin-bottom:24px; }}
  .badge {{ display:inline-block; padding:2px 8px; border-radius:3px; font-size:11px; font-weight:700; margin-right:4px; }}
  .badge-crit  {{ background:#ff000033; color:#ff0000; border:1px solid #ff0000; }}
  .badge-high  {{ background:#ff444433; color:#ff4444; border:1px solid #ff4444; }}
  .badge-med   {{ background:#ffd70033; color:#ffd700; border:1px solid #ffd700; }}
  .badge-low   {{ background:#39ff1433; color:#39ff14; border:1px solid #39ff14; }}
  .badge-info  {{ background:#88888822; color:#888;    border:1px solid #444; }}
  .section {{ background:var(--surface); border:1px solid var(--border); border-radius:6px; padding:16px; margin-bottom:16px; }}
  .finding {{ padding:8px 0; border-bottom:1px solid var(--border); display:flex; gap:12px; align-items:flex-start; }}
  .finding:last-child {{ border-bottom:none; }}
  .finding-val {{ color:var(--cyan); font-family:monospace; font-size:12px; }}
  .finding-ctx {{ color:var(--dim); font-size:11px; margin-top:2px; }}
  .stat-grid {{ display:grid; grid-template-columns:repeat(auto-fit,minmax(140px,1fr)); gap:12px; margin:12px 0; }}
  .stat {{ background:#1a1a1a; border:1px solid var(--border); border-radius:4px; padding:12px; text-align:center; }}
  .stat-val {{ font-size:24px; font-weight:700; color:var(--accent); }}
  .stat-lbl {{ font-size:11px; color:var(--dim); text-transform:uppercase; letter-spacing:1px; margin-top:2px; }}
  ul {{ padding-left:20px; }}
  li {{ margin:4px 0; color:var(--dim); font-size:13px; }}
  li span {{ color:var(--text); }}
  code {{ background:#1e1e1e; padding:1px 5px; border-radius:3px; font-size:12px; color:var(--cyan); }}
  .toc a {{ color:var(--cyan); text-decoration:none; font-size:12px; }}
  .toc a:hover {{ color:var(--accent); }}
  .footer {{ margin-top:32px; padding-top:16px; border-top:1px solid var(--border); color:var(--dim); font-size:11px; text-align:center; }}
</style>
</head>
<body>
<h1>⚡ OMEGA INTELLIGENCE BRIEF</h1>
<div class="meta">Target: <strong style="color:var(--cyan)">{target}</strong> &nbsp;·&nbsp; Generated: {timestamp} &nbsp;·&nbsp; omega-cli v1.6.0</div>

<div class="stat-grid">
  {stat_cards}
</div>

{sections}

<div class="footer">Generated by omega-cli v1.6.0 — For authorized use only</div>
</body>
</html>"""


def _severity_badge(score: float) -> str:
    if score >= 80: return '<span class="badge badge-crit">CRITICAL</span>'
    if score >= 60: return '<span class="badge badge-high">HIGH</span>'
    if score >= 40: return '<span class="badge badge-med">MEDIUM</span>'
    if score >= 20: return '<span class="badge badge-low">LOW</span>'
    return '<span class="badge badge-info">INFO</span>'


def _load_reports(target: str, report_dir: str, hours: int = 168) -> list[dict]:
    safe = re.sub(r"[^a-zA-Z0-9_.-]", "_", target)
    pattern = os.path.join(report_dir, f"*{safe}*.json")
    files = sorted(glob.glob(pattern), key=os.path.getmtime, reverse=True)
    cutoff = datetime.datetime.now().timestamp() - hours * 3600
    reports = []
    for fpath in files:
        if os.path.getmtime(fpath) < cutoff:
            continue
        try:
            with open(fpath) as f:
                data = json.load(f)
            data["_module"] = os.path.basename(fpath).split("_")[0]
            data["_mtime"] = os.path.getmtime(fpath)
            reports.append(data)
        except Exception:
            continue
    return reports


def _compile_brief(target: str, reports: list[dict]) -> dict[str, Any]:
    brief: dict[str, Any] = {
        "target": target,
        "generated": datetime.datetime.utcnow().isoformat() + "Z",
        "report_count": len(reports),
        "modules": [],
        "key_findings": [],
        "ips": set(), "domains": set(), "emails": set(),
        "cves": set(), "breaches": [], "ports": set(),
        "risk_score": 0.0,
    }

    for data in reports:
        module = data.get("_module", "?")
        if module not in brief["modules"]:
            brief["modules"].append(module)

        # IPs
        for ip in re.findall(r"\b(?:\d{1,3}\.){3}\d{1,3}\b", json.dumps(data)):
            if ip not in ("127.0.0.1", "0.0.0.0", "255.255.255.255"):
                brief["ips"].add(ip)

        # Domains/subdomains
        for d in (data.get("subdomains") or []):
            if isinstance(d, str):
                brief["domains"].add(d)

        # Emails
        for e in re.findall(r"[a-zA-Z0-9._%+\-]+@[a-zA-Z0-9.\-]+\.[a-zA-Z]{2,}", json.dumps(data)):
            brief["emails"].add(e.lower())

        # CVEs
        for c in re.findall(r"CVE-\d{4}-\d{4,7}", json.dumps(data), re.I):
            brief["cves"].add(c.upper())

        # Ports
        for p in (data.get("ports") or []):
            port_num = p.get("port", p) if isinstance(p, dict) else p
            if isinstance(port_num, int):
                brief["ports"].add(port_num)

        # Breaches
        for b in (data.get("hibp_breaches") or data.get("breaches") or []):
            if isinstance(b, dict):
                brief["breaches"].append(b.get("Name", "?"))

        # Key findings from riskcore
        if module == "riskcore":
            brief["risk_score"] = data.get("overall_score", 0.0)

        # Key findings
        if data.get("c2_flags"):
            brief["key_findings"].append({"severity": "CRITICAL", "module": module,
                                          "finding": f"C2 indicators: {', '.join(data['c2_flags'][:3])}"})
        if data.get("active_content"):
            brief["key_findings"].append({"severity": "HIGH", "module": module,
                                          "finding": "Document contains active content (JS/macros)"})
        for sec in (data.get("secrets") or [])[:2]:
            brief["key_findings"].append({"severity": "CRITICAL", "module": module,
                                          "finding": f"Exposed secret: {sec.get('type','?')}"})

    # Convert sets to sorted lists
    brief["ips"]     = sorted(brief["ips"])
    brief["domains"] = sorted(brief["domains"])[:20]
    brief["emails"]  = sorted(brief["emails"])[:15]
    brief["cves"]    = sorted(brief["cves"])
    brief["ports"]   = sorted(brief["ports"])

    # Score contribution from findings
    if not brief["risk_score"]:
        brief["risk_score"] = min(
            len(brief["cves"]) * 8 + len(brief["breaches"]) * 10 +
            len(brief["key_findings"]) * 15, 100.0
        )

    return brief


def _render_md(brief: dict) -> str:
    ts = brief["generated"][:19].replace("T", " ")
    lines = [
        f"# Omega Intelligence Brief — {brief['target']}",
        f"",
        f"**Generated:** {ts} UTC  |  **Modules:** {len(brief['modules'])}  |  **omega-cli v1.6.0**",
        f"",
        f"## Executive Summary",
        f"",
        f"| Metric | Count |",
        f"|--------|-------|",
        f"| IP Addresses | {len(brief['ips'])} |",
        f"| Domains/Subdomains | {len(brief['domains'])} |",
        f"| Email Addresses | {len(brief['emails'])} |",
        f"| CVEs | {len(brief['cves'])} |",
        f"| Data Breaches | {len(brief['breaches'])} |",
        f"| Open Ports | {len(brief['ports'])} |",
        f"| Risk Score | {brief['risk_score']:.1f}/100 |",
        f"",
    ]

    if brief["key_findings"]:
        lines += ["## Key Findings", ""]
        for f in brief["key_findings"][:10]:
            lines.append(f"- **[{f['severity']}]** `{f['module']}` — {f['finding']}")
        lines.append("")

    if brief["cves"]:
        lines += ["## CVEs Identified", ""]
        for c in brief["cves"][:15]:
            lines.append(f"- `{c}`")
        lines.append("")

    if brief["ips"]:
        lines += ["## IP Addresses", ""]
        lines.append(", ".join(f"`{ip}`" for ip in brief["ips"][:20]))
        lines.append("")

    if brief["domains"]:
        lines += ["## Subdomains / Domains", ""]
        for d in brief["domains"][:15]:
            lines.append(f"- `{d}`")
        lines.append("")

    if brief["emails"]:
        lines += ["## Email Addresses", ""]
        for e in brief["emails"][:10]:
            lines.append(f"- `{e}`")
        lines.append("")

    lines += [
        "## Modules Analysed",
        "",
        ", ".join(f"`{m}`" for m in brief["modules"]),
        "",
        "---",
        "*Generated by omega-cli v1.6.0 — For authorized use only*",
    ]
    return "\n".join(lines)


def _render_html(brief: dict) -> str:
    ts = brief["generated"][:19].replace("T", " ") + " UTC"

    stat_cards = "".join(f"""
    <div class="stat">
      <div class="stat-val">{val}</div>
      <div class="stat-lbl">{lbl}</div>
    </div>""" for lbl, val in [
        ("IPs",       len(brief["ips"])),
        ("Domains",   len(brief["domains"])),
        ("Emails",    len(brief["emails"])),
        ("CVEs",      len(brief["cves"])),
        ("Breaches",  len(brief["breaches"])),
        ("Ports",     len(brief["ports"])),
        ("Risk Score",f"{brief['risk_score']:.0f}/100"),
        ("Modules",   len(brief["modules"])),
    ])

    sections = []

    if brief["key_findings"]:
        items = "".join(f"""
        <div class="finding">
          {_severity_badge({"CRITICAL":90,"HIGH":65,"MEDIUM":45,"LOW":20,"INFO":5}.get(f["severity"],5))}
          <div>
            <div class="finding-val">[{f["module"]}] {f["finding"]}</div>
          </div>
        </div>""" for f in brief["key_findings"][:10])
        sections.append(f'<div class="section"><h2>⚠ Key Findings</h2>{items}</div>')

    if brief["cves"]:
        cve_html = " ".join(f'<code>{c}</code>' for c in brief["cves"][:20])
        sections.append(f'<div class="section"><h2>🔴 CVEs Identified ({len(brief["cves"])})</h2><p style="margin-top:8px">{cve_html}</p></div>')

    if brief["ips"]:
        ip_html = " ".join(f'<code>{ip}</code>' for ip in brief["ips"][:20])
        sections.append(f'<div class="section"><h2>🌐 IP Addresses ({len(brief["ips"])})</h2><p style="margin-top:8px">{ip_html}</p></div>')

    if brief["domains"]:
        dom_html = "<ul>" + "".join(f"<li><span>{d}</span></li>" for d in brief["domains"][:20]) + "</ul>"
        sections.append(f'<div class="section"><h2>🔗 Domains / Subdomains ({len(brief["domains"])})</h2>{dom_html}</div>')

    if brief["emails"]:
        em_html = " ".join(f'<code>{e}</code>' for e in brief["emails"][:15])
        sections.append(f'<div class="section"><h2>📧 Email Addresses ({len(brief["emails"])})</h2><p style="margin-top:8px">{em_html}</p></div>')

    mods_html = " ".join(f'<code>{m}</code>' for m in brief["modules"])
    sections.append(f'<div class="section"><h2>📦 Modules Analysed</h2><p style="margin-top:8px">{mods_html}</p></div>')

    return HTML_BRIEF.format(
        target=brief["target"],
        timestamp=ts,
        stat_cards=stat_cards,
        sections="\n".join(sections),
    )


def run(target: str, report_dir: str = "", output: str = "", hours: int = 168,
        fmt: str = "html", open_browser: bool = False):
    rdir = report_dir or os.path.expanduser("~/.omega/reports")
    console.print(Panel(
        f"[bold #ff2d78]📋  Intelligence Briefing[/bold #ff2d78] — [cyan]{target}[/cyan]",
        box=box.ROUNDED
    ))

    with console.status("[cyan]Loading recent reports…"):
        reports = _load_reports(target, rdir, hours=hours)
    console.print(f"[dim]Loaded {len(reports)} report(s) from the last {hours}h[/dim]")

    if not reports:
        console.print("[yellow]No reports found. Run omega auto <target> first.[/yellow]")
        return

    with console.status("[cyan]Compiling intelligence brief…"):
        brief = _compile_brief(target, reports)

    console.print(f"\n[bold]Summary:[/bold]")
    console.print(f"  IPs: {len(brief['ips'])}  Domains: {len(brief['domains'])}  "
                  f"Emails: {len(brief['emails'])}  CVEs: {len(brief['cves'])}  "
                  f"Breaches: {len(brief['breaches'])}")
    console.print(f"  Risk Score: [bold #ff2d78]{brief['risk_score']:.1f}/100[/bold #ff2d78]")
    console.print(f"  Modules: {', '.join(brief['modules'])}")

    ts = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    safe = re.sub(r"[^a-zA-Z0-9_.-]", "_", target)
    os.makedirs(rdir, exist_ok=True)

    if fmt in ("html", "both"):
        html_out = output or os.path.join(rdir, f"briefing_{safe}_{ts}.html")
        with open(html_out, "w", encoding="utf-8") as f:
            f.write(_render_html(brief))
        sz = os.path.getsize(html_out)
        console.print(f"\n[bold green]✓  HTML brief:[/bold green] {html_out} ({sz:,} bytes)")
        if open_browser:
            import webbrowser
            webbrowser.open(f"file://{os.path.abspath(html_out)}")

    if fmt in ("md", "markdown", "both"):
        md_out = os.path.join(rdir, f"briefing_{safe}_{ts}.md")
        with open(md_out, "w") as f:
            f.write(_render_md(brief))
        console.print(f"[bold green]✓  Markdown brief:[/bold green] {md_out}")

    json_out = os.path.join(rdir, f"briefing_{safe}_{ts}.json")
    with open(json_out, "w") as f:
        json.dump(brief, f, indent=2)
    console.print(f"[dim]JSON data → {json_out}[/dim]")
