"""PDF report exporter — converts omega findings to a styled PDF."""
import json
import os
from datetime import datetime
from pathlib import Path
from rich.console import Console
from rich.panel import Panel

console = Console()

_HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>OMEGA Report — {target}</title>
<style>
  @import url('https://fonts.googleapis.com/css2?family=Share+Tech+Mono&family=Inter:wght@300;400;600;700&display=swap');
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{
    background: #0d0d0d;
    color: #e0e0e0;
    font-family: 'Inter', sans-serif;
    padding: 0;
  }}
  .cover {{
    background: linear-gradient(135deg, #1a0010 0%, #0d0d0d 60%);
    min-height: 100vh;
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    padding: 60px;
    page-break-after: always;
    border-bottom: 2px solid #ff2d78;
  }}
  .logo {{
    font-family: 'Share Tech Mono', monospace;
    font-size: 3.5rem;
    background: linear-gradient(90deg, #ff2d78, #ff85b3);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    background-clip: text;
    letter-spacing: 0.3em;
    margin-bottom: 0.3em;
  }}
  .subtitle {{
    color: #ff85b3;
    font-size: 1.1rem;
    letter-spacing: 0.2em;
    text-transform: uppercase;
    margin-bottom: 3rem;
  }}
  .cover-meta {{ text-align: center; }}
  .cover-target {{
    font-size: 2rem;
    color: #ffffff;
    font-weight: 700;
    margin-bottom: 0.5em;
  }}
  .cover-date {{ color: #888; font-size: 0.9rem; margin-bottom: 2rem; }}
  .badge {{
    display: inline-block;
    padding: 4px 14px;
    border-radius: 20px;
    font-size: 0.8rem;
    font-weight: 600;
    letter-spacing: 0.05em;
  }}
  .badge-pink {{ background: #ff2d7822; color: #ff2d78; border: 1px solid #ff2d7855; }}
  .content {{ padding: 40px 60px; max-width: 960px; margin: 0 auto; }}
  h1 {{ color: #ff2d78; font-size: 1.8rem; margin: 2rem 0 1rem; border-bottom: 1px solid #ff2d7844; padding-bottom: 0.4em; }}
  h2 {{ color: #ff85b3; font-size: 1.2rem; margin: 1.5rem 0 0.5rem; }}
  .section {{
    background: #111;
    border: 1px solid #222;
    border-left: 3px solid #ff2d78;
    border-radius: 6px;
    padding: 20px 24px;
    margin: 16px 0;
  }}
  .section-title {{
    font-size: 0.75rem;
    text-transform: uppercase;
    letter-spacing: 0.15em;
    color: #ff85b3;
    margin-bottom: 12px;
    font-weight: 600;
  }}
  table {{ width: 100%; border-collapse: collapse; margin: 8px 0; font-size: 0.88rem; }}
  th {{ background: #1a0010; color: #ff85b3; padding: 8px 12px; text-align: left; font-weight: 600; font-size: 0.8rem; text-transform: uppercase; letter-spacing: 0.08em; }}
  td {{ padding: 6px 12px; border-bottom: 1px solid #1e1e1e; color: #ccc; }}
  tr:hover td {{ background: #161616; }}
  code {{ font-family: 'Share Tech Mono', monospace; background: #1a1a1a; padding: 2px 6px; border-radius: 3px; color: #ff85b3; font-size: 0.85em; }}
  pre {{ background: #111; border: 1px solid #222; border-radius: 6px; padding: 16px; overflow-x: auto; font-family: 'Share Tech Mono', monospace; font-size: 0.82rem; color: #aaa; }}
  .stat {{ display: inline-block; margin: 6px 12px 6px 0; }}
  .stat-num {{ font-size: 2rem; font-weight: 700; color: #ff2d78; display: block; line-height: 1; }}
  .stat-label {{ font-size: 0.75rem; color: #888; text-transform: uppercase; letter-spacing: 0.1em; }}
  .footer {{ text-align: center; color: #333; font-size: 0.75rem; padding: 40px; border-top: 1px solid #1a1a1a; margin-top: 60px; }}
  @media print {{
    .cover {{ page-break-after: always; }}
    body {{ background: white; color: #111; }}
    .logo {{ -webkit-text-fill-color: #ff2d78; }}
    .section {{ background: #f9f9f9; border-color: #eee; }}
    th {{ background: #f0f0f0; color: #333; }}
  }}
</style>
</head>
<body>

<div class="cover">
  <div class="logo">OMEGA</div>
  <div class="subtitle">OSINT &amp; Passive Recon Report</div>
  <div class="cover-meta">
    <div class="cover-target">{target}</div>
    <div class="cover-date">Generated: {date}</div>
    <span class="badge badge-pink">CONFIDENTIAL</span>
  </div>
</div>

<div class="content">
  <h1>Findings</h1>
  {sections}
</div>

<div class="footer">
  Generated by omega-cli v0.5.0 — OSINT &amp; Passive Recon Toolkit &nbsp;|&nbsp; {date}
</div>

</body>
</html>"""


def _render_section(title: str, data) -> str:
    html = f'<div class="section"><div class="section-title">{title}</div>'
    if isinstance(data, dict):
        html += "<table><tbody>"
        for k, v in data.items():
            vstr = str(v)[:300].replace("<", "&lt;").replace(">", "&gt;")
            html += f"<tr><td><code>{k}</code></td><td>{vstr}</td></tr>"
        html += "</tbody></table>"
    elif isinstance(data, list):
        if data and isinstance(data[0], dict):
            keys = list(data[0].keys())[:6]
            html += "<table><thead><tr>"
            for k in keys:
                html += f"<th>{k}</th>"
            html += "</tr></thead><tbody>"
            for row in data[:50]:
                html += "<tr>"
                for k in keys:
                    val = str(row.get(k, ""))[:120].replace("<", "&lt;").replace(">", "&gt;")
                    html += f"<td>{val}</td>"
                html += "</tr>"
            html += "</tbody></table>"
        else:
            html += "<ul style='padding-left:20px;list-style:disc;color:#aaa;'>"
            for item in data[:50]:
                item_str = str(item)[:200].replace("<", "&lt;").replace(">", "&gt;")
                html += f"<li style='margin:3px 0;'>{item_str}</li>"
            html += "</ul>"
    else:
        val = str(data)[:500].replace("<", "&lt;").replace(">", "&gt;")
        html += f"<pre>{val}</pre>"
    html += "</div>"
    return html


def export_pdf(target: str, findings: dict, output_path: str = "") -> str:
    """Export findings to a styled PDF (via weasyprint or as HTML fallback)."""
    date_str = datetime.now().strftime("%Y-%m-%d %H:%M UTC")
    sections_html = ""

    for module, data in findings.items():
        sections_html += _render_section(module.upper(), data)

    html = _HTML_TEMPLATE.format(
        target=target,
        date=date_str,
        sections=sections_html,
    )

    output_dir = Path.home() / "omega-reports"
    output_dir.mkdir(parents=True, exist_ok=True)
    safe_target = target.replace(".", "_").replace("/", "_").replace(":", "_")

    if not output_path:
        output_path = str(output_dir / f"omega_{safe_target}_{datetime.now().strftime('%Y%m%d_%H%M')}.pdf")

    html_path = output_path.replace(".pdf", ".html")
    Path(html_path).write_text(html, encoding="utf-8")

    # Try weasyprint for real PDF
    try:
        import weasyprint
        weasyprint.HTML(string=html).write_pdf(output_path)
        console.print(f"[green]✓[/] PDF report saved: [cyan]{output_path}[/]")
        return output_path
    except ImportError:
        pass

    # Fallback: try wkhtmltopdf
    try:
        ret = os.system(f'wkhtmltopdf --quiet "{html_path}" "{output_path}" 2>/dev/null')
        if ret == 0 and Path(output_path).exists():
            console.print(f"[green]✓[/] PDF report saved: [cyan]{output_path}[/]")
            return output_path
    except Exception:
        pass

    # Final fallback: HTML only
    console.print(f"[yellow]⚠  PDF engine not found — saved as HTML:[/] [cyan]{html_path}[/]")
    console.print("[dim]  Install weasyprint for PDF:  pip install weasyprint[/]")
    console.print("[dim]  Or install wkhtmltopdf:      sudo apt install wkhtmltopdf[/]")
    return html_path


def run(target: str, findings: dict = None, output: str = ""):
    """Generate a styled PDF/HTML report."""
    console.print(Panel(
        f"[bold #ff2d78]📄 Report Generator[/]\n[dim]Target:[/] [cyan]{target}[/]",
        border_style="#ff85b3",
    ))

    if findings is None:
        findings = {"note": "No findings provided — run omega recon first"}

    path = export_pdf(target, findings, output)
    return {"target": target, "report_path": path}
